### ISSUE TITLE
Private shared decklist view is delayed

### ISSUE THREAD

**Issue by frogamic** [Null-Signal-Games/netrunnerdb#141] opened 2017-09-18 03:49 UTC
The data served by the api endpoint for private shared decklists (api/2.0/public/deck/xxx) does not show updates that are visible in the frontend view, for example:
https://netrunnerdb.com/en/deck/view/1002142 has been updated to remove the 2x pad factory and add 2x honeyfarm.
https://netrunnerdb.com/api/2.0/public/deck/1002142 still shows 2 pad factory

**Comment by x3N1GM4x** [comment] 2018-12-07 15:52
I'm not able to reproduce this currently - I tested with one of my own decks and making changes reflected immediately in both the API and the front end.

Are you still experiencing this issue?

**Comment by NoahTheDuke** [comment] 2018-12-07 18:19
I suspect this is because of caching in some fashion. Looking at the json now, there are no Pad Factories present.

**Comment by plural** [comment] 2022-03-06 05:43
closing out issues we couldn't reproduce.

**Closed as completed by plural** 2022-03-06 05:43 UTC
Labels: cannot reproduce, api
