### ISSUE TITLE
Switching language in search result page fails

### ISSUE THREAD

**Issue by pjhades** [Null-Signal-Games/netrunnerdb#99] opened 2017-04-08 03:23 UTC
The search result page has a URL like `https://netrunnerdb.com/find/?q=medium`, if we switch the language, it becomes `https://netrunnerdb.com/find/?_locale=zh` which would not show any card information.

I think if the search result contains only one card, the card page should be displayed instead of the search page, then switching the language would not be a problem.

This may be easy to fix I guess.

**Comment by plural** [comment] 2022-03-06 05:43
closing out issues we couldn't reproduce.

**Closed as completed by plural** 2022-03-06 05:43 UTC
Labels: bug, cannot reproduce
