### ISSUE TITLE
Strip html from card text when searching for keywords

### ISSUE THREAD

**Issue by jordahlk** [Null-Signal-Games/netrunnerdb#49] opened 2016-09-12 20:46 UTC
Currently, you have to search like this in order to get results with a bolded keyword:

x:"<strong>code gate</strong> subroutine"

If the search was operating against card text that has been stripped of HTML tags, it should be more intuitive.

**Comment by plural** [comment] 2019-05-12 20:59
I think this is a duplicate of #318

**Closed as completed by plural** 2019-05-12 20:59 UTC
Labels: duplicate
