### ISSUE TITLE
Resetting password does not send an email to change password.

### ISSUE THREAD

**Issue by Krankenste1n** [Null-Signal-Games/netrunnerdb#235] opened 2018-07-14 09:14 UTC
I cannot create a new account because my email is already in use and the "Forgot your Password" does not actually send an email. All usual folders have been checked but no email has been received.

**Comment by x3N1GM4x** [comment] 2018-12-03 16:58
This looks like a duplicate of #232. Suggest we close and combine.

**Closed as completed** 2018-12-03 17:19 UTC

**Comment by x3N1GM4x** [comment] 2019-05-18 14:25
#232 has now been resolved, so password reset emails should be working again.
