### ISSUE TITLE
No email after reset password

### ISSUE THREAD

**Issue by Ligaze** [Null-Signal-Games/netrunnerdb#249] opened 2018-10-23 12:18 UTC
I will come back to netrunner and ive forgot my password but the reset password doesn't send email (i check the spam folder )

**Comment by x3N1GM4x** [comment] 2018-12-03 16:58
This looks like a duplicate of #232. Suggest we close and combine.

**Comment by NoahTheDuke** [comment] 2018-12-03 17:19
Agreed.

**Closed as completed by NoahTheDuke** 2018-12-03 17:19 UTC

**Comment by x3N1GM4x** [comment] 2019-05-18 14:25
#232 has now been resolved, so password reset emails should be working again.
