### ISSUE TITLE
deck/view/ does not show MWL influence stars and lowered influence

### ISSUE THREAD

**Issue by dranimrev** [Null-Signal-Games/netrunnerdb#95] opened 2017-03-22 13:48 UTC
When editing deck, stars are visible and influence is correctly lowered and displayed. 
When going to view mode on finished deck, stars are not visible and influence is not lowered accordingly to MWL. 
Legality was set to: NAPD MWL 1.1 (active)

![los](https://cloud.githubusercontent.com/assets/19939974/24200644/07481612-0f0e-11e7-9821-18fad5cb371c.jpg)

**Comment by alsciende** [comment] 2017-03-23 11:08
Duplicate of https://github.com/Alsciende/netrunnerdb/issues/73

**Comment by plural** [comment] 2019-05-28 00:38
ok, this has been fixed and deployed!

**Closed as completed by plural** 2019-05-28 00:38 UTC
Labels: bug
