### ISSUE TITLE
Sort order incorrect when viewing cycles

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#407] opened 2020-01-20 16:13 UTC
When using the Search bar to find a cycle (c:5, for example) the cards are displayed out of order when sorting by name and viewing as images. Seems to be correct in other formats (as a list etc.)

Seen here is Silhouette appearing first when sorting by name.

![Screenshot_20200120-150013_Chrome](https://user-images.githubusercontent.com/39098450/72741520-b625f080-3b9f-11ea-91f0-9e7771d3cb3c.jpg)

**Comment by plural** [comment] 2020-01-22 14:41
It looks like this was also caused by the spacing issues, because the values in the sort option dropdowns were wrong. Looks like this is fixed now by #410

**Closed as completed by plural** 2020-01-22 14:41 UTC
Labels: bug
