### ISSUE TITLE
Warning about agendas from a different faction

### ISSUE THREAD

**Issue by jojondro** [Null-Signal-Games/netrunnerdb#158] opened 2017-10-06 21:42 UTC
The last deck I modify today, after the MWL 2.0 was applied to the site, is showing me a warning about using agendas from a different faction. 
I know they are all in faction (Weyland) except for GFI which I think is causing the issue.

EDIT: I'm modifying anothe deck, Jinteki, and it has the same problem. This one doesn't have GFI but it has Corporate Sales Team, a neutral one.

**Comment by alsciende** [comment] 2017-10-06 21:43
Can you save that deck again and check if the problem is still present?

**Comment by jojondro** [comment] 2017-10-06 21:44
Did it a couple of times with bboth decks.

**Comment by alsciende** [comment] 2017-10-06 21:48
Indeed -- looks like I can't fix a simple bug the first time. But it's fixed now. Thanks!

**Closed as completed by alsciende** 2017-10-06 21:48 UTC
