### ISSUE TITLE
Feature Request: Move Between Sets

### ISSUE THREAD

**Issue by NoahTheDuke** [Null-Signal-Games/netrunnerdb#113] opened 2017-05-26 17:16 UTC
I find myself frequently looking at specific sets and wishing I could click a button to move to the next or previous chronological pack, like moving back and forth between cards based on set number.

**Comment by NoahTheDuke** [comment] 2018-03-09 15:03
How helpful would this be if I, without any php knowledge, hack together a rough equivalent of what I think should happen? I looked over the code and found where the magic happens, so potentially could make it work, but it would be hacky and def not run on the first try.

Would doing that help at all?

**Comment by plural** [comment] 2019-12-28 01:26
This is basically a duplicate of #67 , so I'm going to close this one out in favor of the original request.

**Closed as completed** 2019-12-28 01:27 UTC
Labels: duplicate, enhancement
