### ISSUE TITLE
Collection settings not saving

### ISSUE THREAD

**Issue by drspaceman** [Null-Signal-Games/netrunnerdb#84] opened 2017-01-18 19:08 UTC
Quorum appears to be available now, but I can't find any Quorum cards when searching while editing a deck.  Also, selecting Quorum manually under Collection doesn't save.

**Comment by plural** [comment] 2022-03-06 05:43
closing out issues we couldn't reproduce.

**Closed as completed by plural** 2022-03-06 05:43 UTC
Labels: bug, cannot reproduce
