### ISSUE TITLE
Searching decklists by author doesn't return complete list

### ISSUE THREAD

**Issue by davewiebe** [Null-Signal-Games/netrunnerdb#93] opened 2017-03-08 22:10 UTC
When viewing my member profile (https://netrunnerdb.com/en/profile/25373/dawiebe) I can see that I have 5 published decklists (that is correct).

When clicking on the 5 decklists link, I'm taken to a page that only shows 2 decks (https://netrunnerdb.com/en/decklists/find?author=dawiebe), where did the other 3 go?

**Comment by Absotively** [comment] 2017-04-17 16:21
I have a few notes to add to this:

1. After getting to the incomplete search results page, clicking the "search" button will bring up the complete results. Presumably the search is not correctly handling the absence of the other query parameters that the "search" button submits.

2. The same thing happens with the "Decklists" links on individual card pages.

3. This appears to me to be a duplicate of issue #91.

**Comment by MGillett** [comment] 2017-04-17 20:54
I noticed this today. https://netrunnerdb.com/en/decklists/find?author=tf34 shows 6 decks but hitting "search" again shows 8 decks.

**Comment by Absotively** [comment] 2017-04-17 21:45
Further notes, because apparently I can't stop poking at things:

* Adding only the "is_legal" parameter appears to be sufficient to fix the search.
* All of the decks that are missing when partial results are shown are currently legal.
* All of the decks that show up in the partial results are currently not legal.

I didn't look at a huge number of the broken searches, but I looked at several and they all fit this pattern.

**Closed as completed** 2017-04-23 13:49 UTC
Labels: bug
