### ISSUE TITLE
Incomplete Login-Data

### ISSUE THREAD

**Issue by ANR-PeterPan** [Null-Signal-Games/netrunnerdb#222] opened 2018-04-08 20:35 UTC
When trying to login via abr and only typing Username and no Password, there is some code rejected.
See Issue on [ABR](https://github.com/madarasz/always-be-running/issues/68)

**Comment by x3N1GM4x** [comment] 2019-01-04 09:06
Almost certainly same root cause as #223, so will manage the investigation there and close this Issue as a duplicate.

**Closed as completed by x3N1GM4x** 2019-01-04 09:06 UTC
Labels: duplicate
